# Site settings
title: Amitosh Swain Mahapatra
email: asm@amitosh.in
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amitosh.in" # the base hostname & protocol for your site, e.g. http://example.com

twitter: originalASM
github:  Agathver
linkedin: amitosh-swain

google_analytics: 'UA-73363098-1'
# Build settings
markdown: kramdown

paginate: 6
paginate_path: "/blog/:num/"
permalink: pretty

feed:
  path: /feed/atom.xml

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: 'Amitosh Swain Mahapatra'

gems:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE