# Site settings
title: Amitosh Mahapatra
description: A stream of characters from Amitosh Swain Mahapatra
email: asm@amitosh.in
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amitosh.in" # the base hostname & protocol for your site, e.g. http://example.com

assets_version: 1

twitter:
  username: agathver
github:
  username: agathver
linkedin:
  username: amitosh-swain

social:
  name: Amitosh Swain Mahapatra

lang: en_IN

google_analytics: 'UA-73363098-1'
# Build settings
markdown: kramdown

paginate: 6
paginate_path: "/blog/:num/"
permalink: pretty

feed:
  path: /feed/atom.xml

author:
  name: 'Amitosh Swain Mahapatra'
  twitter: agathver

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor
