# Site settings
title: Amitosh Swain Mahapatra
email: me@amitosh.in
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amitosh.in" # the base hostname & protocol for your site, e.g. http://example.com

twitter: originalASM
github:  Agathver
linkedin: amitosh-swain

# Build settings
markdown: kramdown

paginate: 5
permalink: pretty

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE